name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BING_COOKIES: ${{ secrets.BING_COOKIES }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: poetry install

    - name: Run linter
      run: poetry run ruff check --output-format=github sydney/

    - name: Run type checker
      run: poetry run mypy --ignore-missing-imports sydney/

    # - name: Run tests
    #   run: poetry run pytest --cov --reruns 3
